version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: '10:00'
    timezone: Japan
  commit-message:
    prefix: ci

- package-ecosystem: "gomod"
  directory: "/deps"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: "Japan"
  commit-message:
    prefix: "deps"
